name: Build gni tools

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - arch: aarch64
            api: 24
          - arch: arm
            api: 24
          - arch: i686
            api: 24
          - arch: x86_64
            api: 24

    steps:
    - uses: actions/checkout@v3

    - name: Run a build script
      run: ${{github.workspace}}/build.sh ${{github.workspace}} $ANDROID_NDK_ROOT ${{matrix.arch}} ${{matrix.api}}

    - name: Zip
      run: zip -j gdbserver-${{matrix.arch}}-android.zip ${{github.workspace}}/install/bin/gdbserver

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: gdbserver-${{matrix.arch}}-android.zip
